name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.1.0']
    steps:
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
